### ISSUE TITLE
7-Zip v22.00 with NSIS and HH:mm:ss display

### ISSUE THREAD

**Issue by ericgl** [Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script#2]
Hi,

**7-Zip v22.00** has been released.
Could you please compile this new version with the NSIS support (as usual with your releases)?
Also, please don't forget to display **HH:mm:ss** by default in the date columns.
Thanks!

**Comment by Wilenty** [comment]
Hello ericgl.
I am sorry for late reply, but I was busy with these things:
https://wilenty.wixsite.com/softwarebywilenty/post/repack-of-gimp-2-10-32-1-original-installer
and
https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/issues/1#issuecomment-1166244244
and after that I had to rest a bit.

Don't worry about me, "I have the memory like a elephant", and also I have your issue saved, so... ;)

Can I also ask you for a favor too? Namely, can you support me?
You know, all of these things takes the time, but I don't have the money to finish the house renovation... Which I started (by myself) before, so, because of the health (back) problems I must to pay to someone to finish it, even if I would like to finish it by myself...

**Comment by ericgl** [comment]
Wilenty,
Thank you for releasing this version. Much appreciated.
I have posted a request for donations to you on my Twitter account:
https://twitter.com/1HDBIZ
Cheers!
