### ISSUE TITLE
7-Zip with Type as column

### ISSUE THREAD

**Issue by ericgl** [Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script#6]
Hi Wilenty,

I have another request:
Instead of clicking **View** > **Type** (CTRL+F4), to sort items by file type, could you please add a "Type" column, like in Windows Explorer?
Makes a lot more sense. I'm surprised Igor, the original developer, hasn't made this change himself.
Thanks in advance!

**Comment by Wilenty** [comment]
Hello,
did you asked author of original 7-ZIP, I mean Igor, to make the changes you expect from me?

You know, I don't know whole 7-ZIP code, because it's not mine creation. There are thousands of lines of code in different files, or even more, sometimes connected to each other. So, sorry, but I don't have the motivation to go through whole 7-ZIP code very carefully to find one thing and make changes for it somewhere.

Greetings,
Wilenty

**Comment by ericgl** [comment]
I understand your take.
I prefer to use your version (displaying NSIS, time with seconds, etc...).

Many have already requested this change, yet Igor ignores them:
https://sourceforge.net/p/sevenzip/discussion/search/?q=type+column
No point in opening another discussion. I have added my comment to theirs.

It's just another improvement to keep in mind for a future build...hope you have the time and energy to do it.

**Comment by Wilenty** [comment]
Hello,
thank you for your kind words about my involvement.

I want to be honest about my financial situation, which is not so good, speaking diplomatically. But I don't like talk about it publicly.
My programming activity it's not a hobby after the main job time. I would like to get a bit more income from my internet activity to get money for my basic life needs. I realize that many people in these crazy times can be in similar situation.

There you can read about my efforts from last years:
https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/issues/1#issuecomment-1166244244

I tried to promote myself (i.e. my works) on MDL, even this 7-zip repack, but people are angry at me that I don't shared the modified source, and they reproach me at every possible opportunity (when the arguments in the discussion end), expand the spoiler:
https://forums.mydigitallife.net/threads/solved-copy-folder-structure-tree-not-files-option-in-context-menu.85302/page-2#post-1734249
I reported this post, but his post still exists, and they (Administration/Moderation) won't delete this post, because he make personal fights against to them, but they delete my posts where I wrote about this problem.

I am also trying to help others on InnoSetup forum:
https://groups.google.com/g/innosetup
but, unfortunately they only asked for the source, because I created something new that they can't:
https://groups.google.com/g/innosetup/c/97au5BFk5VU/m/IArq_yziAAAJ
I am preparing to share my InnoSetup works for money with modified IS, to use my own plugins. These plugins contains most of the things that IS does not support, and no one created it in pure IS [code] (for now).

If you want to check the examples I prepared, but they are protected from unpacking and sometimes they are detected as dangerous by some AV, please don't download them, otherwise:
https://www28.zippyshare.com/v/11WafSHY/file.html

So, I hope that now you can realize that I am very busy trying to create new things. I have the hope that it will give me something in the future. So sorry, but I won't spend my time to search what needs to be changed in the 7-Zip source, for now and probably in the future, if people/users don't want to support me, I will not have the motivation to do this. Life costs money, and I won't live without them - unfortunately.

Greetings,
Wilenty

**Comment by ericgl** [comment]
Well,
I'm also trying to make some money on the internet, using my affiliate website (**1HD.BIZ**) and social media. Not much luck yet, but I keep going. I'm working hard to spread the word about it.

As you may already know, I have already made a post on **Twitter** asking people to support your work: https://twitter.com/1HDBIZ/status/1540972144158539777

I hope you will earn some money, because you're a developer that deserves appreciation.
If possible, I suggest you add a "Donate" button/link on your main page (https://github.com/Wilenty).
This way, it will be easier for people to contribute to you.

**Comment by Wilenty** [comment]
Hello Eric.
I decided to look inside the 7-zip source, because you have a similar situation to mine, and Igor is not eager to change.
In the 7-zip source, in one place is the "Type" and in second is the "Extension", which was not easy to track... After I finally found what needs to be changed, I added the extension tab to the main panel of 7-zip. Now you'll have to rematch. :D

Greeting,
Wilenty

**Comment by ericgl** [comment]
Way to go, man!
Looking forward to this new release.

**Comment by Wilenty** [comment]
It's already released:
https://github.com/Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script/releases/tag/v22.00
or on the main. ;)

**Comment by ericgl** [comment]
I have replaced the **7zFM.exe** and tested the new version.
Now there is indeed an **Extension** column. The column is empty, but sorting works.

However, the column appears only in a very specific scenario, when 7-zip is used as an Explorer.
When opening **.7z**, **.EXE**, **DLL** files (and probably other file types), the column is missing there.

**Comment by Wilenty** [comment]
> I have replaced the 7zFM.exe and tested the new version.
> Now there is indeed an Extension column. The column is empty, but sorting works.

I know that the column is empty, probably it's not finished, or needs more changes that I currently did.

> However, the column appears only in a very specific scenario, when 7-zip is used as an Explorer.
> When opening .7z, .EXE, DLL files (and probably other file types), the column is missing there.

Yes, it's used only when you browsing files and folders, like in the Windows Explorer.
When you browsing the .7z, .EXE, DLL files, look in the menu->View, if there's the "Type" option available.

**Comment by Wilenty** [comment]
Hello Eric,
updated to the latest version (v22.01).

I checked the type/extension settings in the 7-zip, and I can't get the extension for all types of archives, because these properties are read from archives properties. So, to make it as you asked there should be a button to change the sorting-type, or two lines of tabs. I don't know how to do it, so you should ask the Igor.

For example 7z-format from 7-zip source:
https://www.7-zip.org/a/7z2201-src.7z -> `CPP\7zip\Archive\7z\7zProperties.cpp`
```c
static const CPropMap kPropMap[] =
{
  { NID::kName, { NULL, kpidPath, VT_BSTR } },
  { NID::kSize, { NULL, kpidSize, VT_UI8 } },
  { NID::kPackInfo, { NULL, kpidPackSize, VT_UI8 } },
  
  #ifdef _MULTI_PACK
  { 100, { "Pack0", kpidPackedSize0, VT_UI8 } },
  { 101, { "Pack1", kpidPackedSize1, VT_UI8 } },
  { 102, { "Pack2", kpidPackedSize2, VT_UI8 } },
  { 103, { "Pack3", kpidPackedSize3, VT_UI8 } },
  { 104, { "Pack4", kpidPackedSize4, VT_UI8 } },
  #endif

  { NID::kCTime, { NULL, kpidCTime, VT_FILETIME } },
  { NID::kMTime, { NULL, kpidMTime, VT_FILETIME } },
  { NID::kATime, { NULL, kpidATime, VT_FILETIME } },
  { NID::kWinAttrib, { NULL, kpidAttrib, VT_UI4 } },
  { NID::kStartPos, { NULL, kpidPosition, VT_UI8 } },

  { NID::kCRC, { NULL, kpidCRC, VT_UI4 } },
  
//  { NID::kIsAux, { NULL, kpidIsAux, VT_BOOL } },
  { NID::kAnti, { NULL, kpidIsAnti, VT_BOOL } }

  #ifndef _SFX
  ,
  { 97, { NULL, kpidEncrypted, VT_BOOL } },
  { 98, { NULL, kpidMethod, VT_BSTR } },
  { 99, { NULL, kpidBlock, VT_UI4 } }
  #endif
};
```
As you see there's no type and/or extension part in the above quoted text...

Greetings,
Wilenty

**Comment by ericgl** [comment]
I see...
Well, I guess I need to nag him now, hehe.
Thanks for looking into it.

**Comment by Wilenty** [comment]
By the way, you have to clearly wrote that a new version has come out. I don't have a time to track all programs, so, please for understanding.
