### ISSUE TITLE
[featurerequest] change project title

### ISSUE THREAD

**Issue by zedd-0** [Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script#7]
hello,

i have some variants of 7-zip.
is it hard to keep them separated, without using too long filenames. 😄 

it would be nice, if you can change the filenames
and the program title to something like:

filename
from: "7z2201-FULL.7z"
to:     "7z2201-Wilenty-Mod_FULL.7z"
or a extreme format like this 😝: "7-Zip-v22.01_Wilenty-Mod_2022-07-18_FULL.7z"

program-title
from: "7-Zip"
to:     "7-Zip Wilenty-Mod"

maybe your github-title, too?
from: "7-Zip-X64-X86-with-Extracting-NSIS-script"
to:     "7-Zip_Wilenty-Mod_X64-X86-with-Extracting-NSIS-script"

or to something else,
so i can easily see where the modification-vendor is.

thanks a lot.

**Comment by Wilenty** [comment]
Hello,
thank you for the information that you use (collect also of) my repack of 7-ZIP.

I don't think that the suggested changes will be useful for other users. So, I think you should change the file-names for yourself, because you make the collection of 7-ZIP.

Bay the way, adding sub-extension inside the file-name will make it suspicious.

I think to archive this (close it), because it takes a loot of the time, and people want more and more, but they don't want to support my work...

Greetings,
Wilenty

**Comment by zedd-0** [comment]
ah. yeah.
somehow I thought so
that you won't put as much energy into it.

no problem.
have a nice day.

**Comment by krystian3w** [comment]
You can try use download attrib in e.g. Violentmonkey https://www.w3schools.com/tags/att_a_download.asp if page allow.

**Comment by Wilenty** [comment]
Hello krystian3w,
thanks for the suggestion to use HTML tag.
But I think that disliking (adding thumbs-down), when you answering to that question is not okay and you should remove it.

I added the "DownloadWithRename.cmd" script based on wget to download all or some files from this 7-zip release with rename (as the file-name says). Before use this cmd script you have to download "wget.exe" (and/or "wget64.exe") from the website mentioned at the top of the script ( https://eternallybored.org/misc/wget/ ).

Greetings,
Wilenty

**Comment by pasha-zzz** [comment]
You may use WinTLS variant of wget - https://github.com/lifenjoiner/wget-for-windows/releases
Not so large as OpenSSL.

**Comment by Wilenty** [comment]
Thank you [pasha-zzz](https://github.com/pasha-zzz) for quick response. It's smaller and it works also, recommend!
